<?php
session_start();
require_once 'header.php'; ?>
  <tr>
    <td align="left" valign="top" bgcolor="#FFFFFF"><img src="images/wightlin.jpg" width="5" height="2" /></td>
  </tr>
  <tr>
    <td align="left" valign="top" bgcolor="#FFFFFF"><img src="images/banner.jpg" width="990" height="252" /></td>
  </tr>
  <tr>
    <td align="left" valign="top" bgcolor="#FFFFFF">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="top" bgcolor="#FFFFFF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td align="left" valign="top" class="txt">&nbsp;</td>
        <td height="30" align="left" valign="top" class="rtxtr"><strong>CSR</strong></td>
        <td align="left" valign="top" class="txt">&nbsp;</td>
      </tr>
      <tr>
        <td width="1%" align="left" valign="top" class="txt">&nbsp;</td>
        <td width="98%" align="left" valign="top" class="txt"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            
            <td width="83%" height="54" align="left" valign="top" class="txt"><div align="justify">
             <span class="suptitxt">Our Corporate Social Responsibilities</span><br />
                Every cent of profit generated by our  company is made with the use of limited natural resources and human involvement.  As a business, we are dedicated to fulfil our environmental and social  responsibilities to God&acute;s creation. 
                <br />
                <br />
             
            </div></td>
          </tr>
        </table></td>
        <td width="1%" align="left" valign="top" class="txt">&nbsp;</td>
      </tr>
      <tr>
        <td align="left" valign="top" class="txt">&nbsp;</td>
        <td align="left" valign="top" class="txt"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="12%" height="144" align="left" valign="top"><img src="images/one.png" width="89" height="143" /></td>
            <td width="88%" align="left" valign="top"><p align="justify"><span class="suptitxt"><strong>&ldquo;One  Ticket One Tree&ldquo;&nbsp;&nbsp;</strong></span><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><br />
                <span class="txt">With each ticket that we sell and make a  profit from, we will sponsor a fruit plant. The main purpose of this project is  toprotect the environment by planting trees. <br />
                <br />
                Why a fruit tree: &nbsp;It is a kind of a &ldquo;tree of life&rdquo;.  On one hand, one single tree is absorbing 20 Kgs of CO2 in a year, and on the  other hand, it is a source of nutrition for the people with the fruits it  bears. It is a long term solution to alleviate hunger and reducing poverty by  enabling people to earn income by selling fruits.</span><br />
                <br />
            </div></td>
          </tr>
        </table></td>
        <td align="left" valign="top" class="txt">&nbsp;</td>
      </tr>
      <tr>
        <td align="left" valign="top" class="txt">&nbsp;</td>
        <td align="left" valign="top" class="txt"><div align="justify"><strong class="suptitxt">&ldquo;Love  your neighbour&rdquo; </strong><br />
          We contribute 5% of our annualprofit  towards a project which protects children or widows.<br />
          <br />
          For the year 2012, we will be supporting  Elisabeth Syr&eacute; Ministries International Inc. It is a Christian children&rsquo;s  orphanage institute dedicated to protecting children.&nbsp; This is one of Elisabeth Syr&eacute;&acute;s legacies:<br />
          <br />
  &ldquo;A Boy of 6, who needs to go to school and has no  school fees - his mom is dying of Aids - his stepfather abuses him - we took  him away from the abusive situation into our care &ndash; we had him checked at the  clinic &ndash; we are in the process of adopting him so that he can stay in our house  and receives proper education and spiritual input&rdquo;.<br />
  <br />
  <strong>Our  5% contribution goes to the following Organization.</strong> <br />
  <br />
          Elisabeth Syr&eacute; Ministries  International Inc. <br />
          International Life Group <br />
          P.O. Box 411 <br />
          Constantia, 7848 <br />
          Cape Town, South Africa <br />
          Tel: 0027-21-713-1272 <br />
          Fax: 0027-21-715-2502 <br />
          Cell (local): 084-463-8827</p></td>
        <td align="left" valign="top" class="txt">&nbsp;</td>
      </tr>
    </table></td>
  </tr>
<?php require_once 'footer.php'; ?>